name: "Ex 1 Promote (Stage)"
on:
  workflow_dispatch:

jobs:
  get-deployment:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-deployment-action.outputs.sha }}
      ref: ${{ steps.get-deployment-action.outputs.ref }}
    steps:
      - uses: tgrnwd/get-deployment@v1
        id: get-deployment-action
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          environment: ex1-dev

  stage:
    runs-on: ubuntu-latest
    environment: ex1-stage
    needs: get-deployment
    steps:
      - run: | 
          echo "${{ needs.get-deployment.outputs.ref }}"
          echo "${{ needs.get-deployment.outputs.sha }}"

      - uses: cardinalby/git-get-release-action@v1
        id: get-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          commitSha: ${{ needs.get-deployment.outputs.sha }}

      - run: | 
          echo "${{ steps.get-release.outputs.tag_name }}"
          echo "${{ steps.get-release.outputs.id }}"

      - uses: robinraju/release-downloader@v1.3
        name: download release asset
        with: 
          repository: ${{ github.repository }}
          tag: ${{ steps.get-release.outputs.tag_name }}
          fileName: "readme.txt"

      - run: |
          cat readme.txt

      - name: Deploy
        run: |
          echo "Deploying to ex1-stage"