name: "Promote to Prod"
on:
  workflow_dispatch:

jobs:
  get-deployment:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-deployment-action.outputs.sha }}
      ref: ${{ steps.get-deployment-action.outputs.ref }}
    steps:
      - uses: tgrnwd/get-deployment@v1
        id: get-deployment-action
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          environment: stage


  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: get-deployment
    steps:

      - uses: cardinalby/git-get-release-action@v1
        id: get-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          commitSha: ${{ needs.get-deployment.outputs.sha }}

      - uses: robinraju/release-downloader@v1.3
        name: download release asset
        with: 
          repository: ${{ github.repository }}
          tag: ${{ steps.get-release.outputs.tag_name }}
          fileName: "*"

      - run: |
          cat release.txt

      - name: Deploy
        run: |
          echo "Deploying to prod"