name: "Deploy to Dev"
on:
  release:
    types:
      - published

jobs:

  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Debug
        run: | 
          echo ${{ github.event.release.tag_name }}

      - name: Download Release
        uses: robinraju/release-downloader@v1.3
        with: 
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
      
      - name: Release echo
        run: |
          cat release.txt

      - name: Deploy
        run: |
          echo "Deploying to dev"